[Icon Theme]
Name=Definitivo
Comment=Tema personalizado
Inherits=Papirus-Dark,Papirus,Adwaita,hicolor

FollowsColorScheme=true

Directories=places/scalable,places/symbolic,apps/scalable

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=22
Type=Fixed

[places/scalable]
Context=Places
Size=128
MinSize=32
MaxSize=512
Type=Scalable

[apps/scalable]
Context=Apps
Size=128
MinSize=32
MaxSize=512
Type=Scalable

